"$schema" = 'https://starship.rs/config-schema.json'

format = """\
$time\
${custom.connection}\
$git_branch\
$directory\
$character\
"""

add_newline = false

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"

[time]
disabled = false
format = "[$time]($style) "
style = ""
time_format = "%I:%M:%S"
use_12hr = false

[custom.connection]
command = 'if [ -n "$SSH_CONNECTION" ]; then echo "ssh:$(hostname -s)"; else echo "local"; fi'
when = true
format = "[$output]($style) "
style = ""


[git_branch]
disabled = false
format = "[$branch(:$remote_branch)$symbol]($style)"
symbol = "@"
style = "bg:overlay"
truncation_length = 100
truncation_symbol = "..."

[directory]
format = '[$path]($style) '
style = ""
truncate_to_repo = true
truncation_length = 3
truncation_symbol = ""
